name: Main
on:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - release/*

concurrency:
  cancel-in-progress: true
  group: main-${{ github.ref }}

jobs:
  test:
    name: Python ${{ matrix.py-version }} Test against k8s v${{ matrix.kubernetes }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py-version: ['3.7', '3.8', '3.9', '3.10']
        kubernetes: ['18', '19', '20', '21', '22', '23', '24']

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py-version }}
    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools wheel
        python -m pip install -U tox tox-gh-actions
        python -m pip install kubernetes==${{ matrix.kubernetes }}.*
    - name: Run tests
      run: tox
    - name: Rename coverage report file
      run: |
        env
        ls .coverage*
        mv .coverage .coverage.k${{ matrix.kubernetes}}.py${{ matrix.py-version }}
    - name: Upload coverage data
      uses: actions/upload-artifact@v3
      with:
        name: coverage-data
        path: ".coverage.*"

  coverage:
    name: Combine coverage data
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install tox and coverage
      run: python -m pip install tox coverage
    - name: Download coverage data
      uses: actions/download-artifact@v3
      with:
        name: coverage-data
    - name: Combine coverage data
      run: |
        coverage combine
        coverage xml
        coverage html -d ./htmlcov
    - name: Upload report to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
    - name: Upload HTML report
      uses: actions/upload-artifact@v3
      with:
        name: html-report
        path: ./htmlcov



  publish:
    if: github.event_name == 'push' && ( startsWith(github.ref, 'refs/tags') || startsWith(github.ref, 'refs/heads/release/') )
    runs-on: ubuntu-latest
    name: Build and Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install build
      - name: Log version
        run: |
          python setup.py --version
      - name: Build
        run: |
          python -m build --wheel --outdir dist/
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}